### ISSUE TITLE
As a developer, I want my commits to be checked by a linter so that code standards are maintained.

### ISSUE THREAD

**Issue by MathieuLamiot** [wp-media/wp-rocket-e2e#2]
**Context**

The wp-rocket-e2e project has a great potential to speed up our development processes: as suggested by @CrochetFeve0251 in #1, every developer could leverage it to automate testing and validation of acceptance criteria. This means that many people will perform small updates regularly on this repository. However, it is currently not up to standards, making it difficult to maintain properly overtime.

Several steps must be taken to make this codebase "production ready".

**Expected behavior**

When a commit is pushed to the repository, a linter must be applied and results must be reported.
The repository must be ready-to-use with a linter locally so that developers can perform checks themselves.

All automatically fixable errors must be fixed. Exceptionally, it is not needed that the linter returns no error for this issue to be closed: several refactoring must occur shortly, so let's not waste time fixing code that will disappear.

**Proposed solution**

We could use eslint:
- It is a well known linter for JS/TS,
- It is easy to set up locally,
- There are github actions available to quickly set up the CI.

**Comment by jeawhanlee** [comment]
### Scope a solution ✅

#### Locally
We will need to install eslint support for typescript as well as eslint:
`npm install --save-dev @typescript-eslint/parser @typescript-eslint/eslint-plugin eslint typescript`
Then we configure eslint:
- Create the .eslintrc
- Add basic configurations
```
{
  "root": true,
  "parser" : "@typescript-eslint/parser",
  "plugins": [
    "@typescript-eslint"
  ],
  "extends" ; [
    "eslint: recommended",
    "plugin:@typescript-eslint/eslint-recommended,
    "plugin:@typescript-eslint/recommended"
  ]
}
```
- Lastly we will add a new command in package.json under `scripts`:
`"lint": "eslint . --ext .ts"` for eslint to run with only files with extension `.ts` so we can now run this using `npm run lint`

#### On Git Actions
We can set up a yml file that will run the new command we just created on every `PR`

```
name: Typescript eslint
on:
  pull_request:
    branches:
      - branch-*

jobs:
  lint:
    runs-on: ubuntu-latest
    name: Run eslint
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - name: Install dependencies
         run: npm ci
       - name: Run Typescript eslint
         run: npm run lint
```
Estimate the effort ✅
[XS]
